name: ğŸ¦º Validate build status

on:
  push:
    branches: [ "alpha" ]
    
  pull_request:
    branches: [ "alpha" ]

jobs:
  build-linux:
    name: ğŸ§ Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: ğŸ”— Checkout source code from github
      uses: actions/checkout@v3

    - name: ğŸ›¤ï¸ Setup the build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: ğŸ§ Prepare the build environment
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/dev_init.sh

    - name: ğŸ§ Built the application
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/dev_release.sh Debug
      env:
        PFXCERT: ${{ secrets.PFXCERT }}
        CERTPASS: ${{ secrets.CERTPASS }}
        
    - name: â¬†ï¸ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-build-linux-${{ github.run_id }}
        path: Release

  build-windows:
    name: ğŸªŸ Windows
    runs-on: windows-latest
    
    steps:
    - name: ğŸ”— Checkout source code from github
      uses: actions/checkout@v3

    - name: ğŸ›¤ï¸ Setup the build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: ğŸ§ Prepare the build environment
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\dev_init.bat

    - name: ğŸ§ Built the application
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\dev_release.bat Debug

    - name: â¬†ï¸ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifact-build-windows-${{ github.run_id }}
        path: Release
