###
### Copyright (c) 2023 Carbon Community 
### All rights reserved
###
name: Branch Merge
concurrency: merge-process-exec

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'From branch'
        required: true
        default: 'preproduction'
        type: choice
        options:
          - develop
          - preview
          - preproduction

      target:
        description: 'Target branch'
        required: true
        default: 'production'
        type: choice
        options:
          - preview
          - production

jobs:
  merge:
    name: üîÉ Merge branches
    runs-on: ubuntu-latest

    steps:
    - name: üîó Checkout source code from github
      uses: actions/checkout@v3

    - name: ‚§µÔ∏è Merge ${{ inputs.source }} into ${{ inputs.target }}
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: ${{ inputs.source }}
        target_branch: ${{ inputs.target }}
        github_token: ${{ secrets.PAT_PUBLIC_REPO }}
        message: |
          Merge ${{ inputs.source }} into ${{ inputs.target }}
