name: ğŸ¦º Validate build status

on:
  push:
    branches: [ "alpha" ]
    
  pull_request:
    branches: [ "alpha" ]

jobs:
  build:
    name: ğŸ”¨ Build Carbon on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    
    steps:
    - name: ğŸ”— Checkout source code from github
      uses: actions/checkout@v3

    - name: ğŸ›¤ï¸ Setup the build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: ğŸ§ Execute the build process on Linux
      if: matrix.os == 'ubuntu-latest'
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/dev_init.sh
        ${GITHUB_WORKSPACE}/Tools/Build/linux/dev_release.sh

    - name: ğŸªŸ Execute the build process on Windows
      shell: cmd
      if: matrix.os == 'windows-latest'
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\dev_init.bat
        %GITHUB_WORKSPACE%\Tools\Build\win\dev_release.bat
