# 
#   ______ _______ ______ ______ _______ _______ 
#  |      |   _   |   __ \   __ \       |    |  |
#  |   ---|       |      <   __ <   -   |       |
#  |______|___|___|___|__|______/_______|__|____|
#                         discord.gg/eXPcNKK4yd
# 
name: Production Build
concurrency: build-1-production

on:
  push:
    branches:
      - production

  schedule:
    - cron: '30 18 * * 4'

  workflow_run:
    workflows: [ "branch-merge" ]
    types:
      - completed
    branches:
      - production

jobs:
  bootstrap:
    name: ðŸ¥¾ Bootstrap
    runs-on: ubuntu-latest

    outputs:
      date:  ${{ steps.step1.outputs.date }}
      clock: ${{ steps.step1.outputs.clock }}
      tag:   ${{ steps.step1.outputs.tag }}
      ref:   ${{ steps.step1.outputs.ref }}
      wipe:  ${{ steps.step1.outputs.wipe }}

    steps:
      - name: ðŸ”— Checkout source code from github
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: ðŸ“… Prepare the environment
        id: step1
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=clock::$(date +'%H:%M:%S')"
          echo "::set-output name=tag::$(date +'%Yd%j')"
          echo "::set-output name=ref::$(git rev-parse --short HEAD)"
          echo "::set-output name=wipe::$( [ $(date +%u) -eq 4 ] && [ $(date +%d) -le 7 ] && echo true || echo false )"

  build-linux:
    name: ðŸ§ Linux
    needs: bootstrap
    runs-on: ubuntu-latest
    continue-on-error: false

    outputs:
      wipe: ${{ needs.bootstrap.outputs.wipe }}
      artifact: build-production-${{ needs.bootstrap.outputs.ref }}-linux
      build_info: Built at ${{ needs.bootstrap.outputs.date }} ${{ needs.bootstrap.outputs.clock }} based on commit ${{ needs.bootstrap.outputs.ref }}.
    
    steps:
    - name: ðŸ”— Checkout source code from github
      uses: actions/checkout@v3
      with:
        ref: production

    - name: ðŸ›¤ï¸ Setup the dotnet build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: ðŸªš Setup the Carbon build environment
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/bootstrap.sh

    - name: ðŸ§ Built Carbon on Linux
      shell: bash
      run: |
        ${GITHUB_WORKSPACE}/Tools/Build/linux/build_release.sh
        
    - name: â¬†ï¸ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-production-${{ needs.bootstrap.outputs.ref }}-linux
        path: Release

  build-windows:
    name: ðŸªŸ Windows
    needs: bootstrap
    runs-on: windows-latest
    continue-on-error: false
    
    steps:
    - name: ðŸ”— Checkout source code from github
      uses: actions/checkout@v3
      with:
        ref: production

    - name: ðŸ›¤ï¸ Setup the dotnet build environment
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: ðŸªš Setup the Carbon build environment
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\bootstrap.bat

    - name: ðŸªŸ Built Carbon on Windows
      shell: cmd
      run: |
        %GITHUB_WORKSPACE%\Tools\Build\win\build_release.bat

    - name: â¬†ï¸ Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-production-${{ needs.bootstrap.outputs.ref }}-windows
        path: Release

  release:
    name: ðŸ’¾ Release
    needs: [ "build-linux", "build-windows" ]
    runs-on: ubuntu-latest

    if: github.event_name == 'workflow_run' || (github.event_name == 'schedule' && needs.build-linux.outputs.wipe == 'true')

    steps:
    - name: â¬‡ï¸ Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ needs.build-linux.outputs.artifact }}
        path: Release/

    - name: ðŸ·ï¸ Update release tag
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        tag_name: production_build
        name: 'Carbon Build (production)'
        body: |
          This is a build of Carbon based on the `production` branch.
          This build is targeted at the general public.

          ### How to install
          1. Download the `Carbon.Patch.zip` archive from the attachments below.
          2. Unzip the archive to the root of your Rust Dedicated Server.
          3. Restart the server and enjoy.
          
          ${{ needs.build-linux.outputs.build_info }}
        files: |
          Release/Carbon.dll
          Release/Carbon.Patch.zip
          Release/Carbon-Unix.dll
          Release/Carbon.Patch-Unix.zip
